### ISSUE TITLE
Reporte |Diseño de TexBox personalizado con Visual Studio|

### ISSUE THREAD

**Issue by KarlaV0** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-KarlaV0#2]
[TAP,Unidad 2,Reporte TexBox.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-KarlaV0/files/6366806/TAP.Unidad.2.Reporte.TexBox.pdf)

**Comment by Brisa-4** [comment]
[3.- Rúbrica reporte de practica.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-KarlaV0/files/6385131/3.-.Rubrica.reporte.de.practica.pdf)

**Comment by Brisa-4** [comment]
20/20
Calificó: Brisa Osorio Ramirez

**Comment by josealfredo79** [comment]
Bien hecho y revisado
